---
title: "Camila-Cortina-ADA-Homework-4"
author: "Camila Cortina"
date: "5/9/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r copied code}
remotes::install_github("joachim-gassen/tidycovid19")
library(tidyverse)
library(patchwork) # for plotting
library(scales) # for log y axis scale
library(collapse) # for `fmode()` to find mode
library(BBmisc) # for %nin%
library(devtools)
library(tidycovid19)

merged <- download_merged_data(cached = TRUE)
merged <- merged %>%
  group_by(country, iso3c) %>%
  arrange(country, iso3c, date) %>%
  ## new code to replace NAs with zeros
  mutate(
    confirmed = ifelse(is.na(confirmed), 0, confirmed),
    deaths = ifelse(is.na(deaths), 0, deaths),
    recovered = ifelse(is.na(recovered), 0, recovered)
  ) %>%
  ## end of new code
  mutate(
    daily_confirmed = confirmed - lag(confirmed, n = 1),
    daily_deaths = deaths - lag(deaths, n = 1),
    daily_recovered = recovered - lag(recovered, n = 1)
  ) %>%
  mutate(
    daily_confirmed = replace_na(daily_confirmed, 0),
    daily_deaths = replace_na(daily_deaths, 0),
    daily_recovered = replace_na(daily_recovered, 0)
  ) %>%
  ungroup() %>%
  arrange(country, iso3c, date)

add_world1 <- merged %>%
  group_by(date) %>%
  arrange(date) %>%
  summarize(
    country = "World", iso3c = NA,
    confirmed = sum(confirmed, na.rm = TRUE),
    deaths = sum(deaths, na.rm = TRUE),
    recovered = sum(recovered, na.rm = TRUE),
    timestamp = fmode(timestamp)
  ) %>%
  mutate(
    daily_confirmed = confirmed - lag(confirmed, n = 1),
    daily_deaths = deaths - lag(deaths, n = 1),
    daily_recovered = recovered - lag(recovered, n = 1)
  ) %>%
  mutate(
    daily_confirmed = replace_na(daily_confirmed, 0),
    daily_deaths = replace_na(daily_deaths, 0),
    daily_recovered = replace_na(daily_recovered, 0)
  ) %>%
  ungroup() %>%
  arrange(country, iso3c, date)

add_world2 <- merged %>%
  group_by(country, iso3c) %>%
  summarize(
    population = fmode(population),
    land_area_skm = fmode(land_area_skm),
    timestamp = fmode(timestamp)
  ) %>%
  ungroup() %>%
  summarize(
    country = "World", iso3c = NA,
    population = sum(population, na.rm = TRUE),
    land_area_skm = sum(land_area_skm, na.rm = TRUE)
  ) %>%
  mutate(pop_density = population / land_area_skm)

add_world <- left_join(add_world1, add_world2, by = c("country", "iso3c"))
merged <- bind_rows(merged, add_world)

cv_data <- pivot_longer(merged,
  cols = c(
    "confirmed", "deaths", "recovered",
    "daily_confirmed", "daily_deaths", "daily_recovered"
  ),
  names_to = "variable", values_to = "cases"
) %>%
  arrange(country, variable, date) %>%
  rename(area = land_area_skm, density = pop_density) %>%
  mutate(rate = cases / population * 10^6) %>%
  ## new code to omit data before 2020-05-11
  filter(date < "2020-05-11")
## end of new code

cv_summary <- function(d, country_list = "World",
                       plot = TRUE, facet = "country",
                       status = c("confirmed", "deaths", "recovered")) {

  # based on `wes_palettes()` GrandBudapest1, IsleofDogs1, IsleofDogs2
  # from the {wesanderson} package
  my_palette <- c(
    "#5B1A18", "#FD6467", "#F1BB7B", "#D67236",
    "#0F0D0E", "#9986A5", "#79402E", "#CCBA72", "#D9D0D3", "#8D8680",
    "#EAD3BF", "#AA9486", "#B6854D", "#39312F", "#1C1718"
  )

  if (facet == "country") {
    fill <- "variable"
    n <- length(unique(d$variable)) / 2
    # need only half of unique # of variable (3)
  }

  if (facet == "variable") {
    fill <- "country"
    n <- length(country_list)
    # need number of countries
  }

  if ("All" %in% country_list) {
    country_list <- unique(d$country)
    country_list <- setdiff(country_list, "World")
  }

  if ("World" %in% country_list) {
    d <- d %>% filter(country %in% country_list)

    totals <- d %>%
      group_by(variable) %>%
      summarize(
        country = "World",
        cases = max(cases),
        population = max(population),
        area = max(area),
        density = max(density),
        rate = max(rate, na.rm = TRUE),
        on = max(date)
      ) %>%
      select(country, variable, cases, population, area, density, rate, on) %>%
      arrange(variable) %>%
      ungroup()
  }

  if ("World" %nin% country_list) {
    d <- d %>% filter(country %in% country_list)
    totals <- d %>%
      group_by(country, variable) %>%
      summarize(
        cases = max(cases),
        population = max(population),
        area = max(area),
        density = max(density),
        rate = max(rate, na.rm = TRUE),
        on = max(date),
        gdp_capita = fmode(gdp_capita),
        income = fmode(income),
        life_expectancy = fmode(life_expectancy),
        max_sd = max(soc_dist),
        max_mr = max(mov_rest)
      ) %>%
      select(
        country, variable, cases, population, area, density, rate,
        gdp_capita, income, life_expectancy, max_sd, max_mr, on
      ) %>%
      arrange(country, variable) %>%
      ungroup()
  }

  if (plot == TRUE) {
    cc <- filter(d, variable %in% status)
    cum_cases_plot <- ggplot(
      data = cc,
      # use the tidy evaluation pronoun .data to slice the chosen fill
      # variable from the data frame
      aes(
        x = date, y = cases + 1, color = .data[[fill]],
        fill = .data[[fill]]
      )
    ) +
      geom_point(size = 0.5) +
      geom_line() +
      # use the tidy evaluation pronoun .data to slice the chosen facet_wrap
      # variable from the data frame
      facet_wrap(~ .data[[facet]], ncol = 5) +
      xlab("Date") +
      ylab("Log Cumulative Cases") +
      scale_y_log10(
        breaks = trans_breaks("log10", function(x) 10^x),
        labels = trans_format("log10", math_format(10^.x))
      ) +
      scale_color_manual(
        aesthetics = c("color", "fill"),
        name = NULL, values = my_palette
      )

    dc <- filter(d, variable %in% paste0("daily_", status))
    daily_cases_plot <- ggplot(
      data = dc,
      aes(
        x = date, y = cases, color = .data[[fill]],
        fill = .data[[fill]]
      )
    ) +
      geom_point(size = 0.5) +
      geom_line() +
      facet_wrap(~ .data[[facet]], ncol = 5) +
      xlab("Date") +
      ylab("Daily Cases") +
      scale_color_manual(
        aesthetics = c("color", "fill"),
        name = NULL, values = my_palette
      )
  }

  if (plot == TRUE) {
    return(list(
      totals = totals,
      cum_cases_plot = cum_cases_plot,
      daily_cases_plot = daily_cases_plot
    ))
  } else {
    return(list(totals = totals))
  }
}
```

##Challenge 1
```{r}
detach(package:MASS)
cv_summary(cv_data)
```

##Challenge 2
```{r}
cv_summary(cv_data, country_list = c("United States", "United Kingdom", "Canada", "France", "Germany", "Italy", "Japan")) #faceted by country 

cv_summary(cv_data, country_list = c("United States", "United Kingdom", "Canada", "France", "Germany", "Italy", "Japan"), facet = "variable") #faceted by variable 
```

##Challenge 3
```{r}
d<- cv_data %>% cv_summary(country_list = "All", plot = FALSE)
d<- as.tibble(d)
d<- d %>% filter(totals$population >= 1000000)
d

unique(d$totals$country) #154 countries with over 1 million people
```

##Challenge 4
```{r}
overall<- d %>% filter(d$totals$variable == "confirmed") %>% arrange(desc(totals$rate))
head(overall, n = 10) #these 10 countries had the highest rate of confirmed cases

daily <- d %>% filter(d$totals$variable == "daily_confirmed") %>% arrange(desc(totals$cases))
head(daily, n=10) #These 10 countries had the highest single-dat rates


```

##Challenge 5
```{r}
cv_data<- cv_data %>% arrange(rate) %>% filter(rate > 0) #had to filter out zeros because it won't let you take the log of 0
model<- lm(log(rate)~ log(density) + log(population) + log(gdp_capita) + income, data = cv_data)

summary(model) #density, population, gdp, and lower middle income are significant predictors 

#testing normality of density
qqnorm(log(cv_data$density), main = "QQ Plot - Random Normal Variable")
qqline(log(cv_data$density), col = "gray")
hist(log(cv_data$density))
#testing normality of population
qqnorm(log(cv_data$population), main = "QQ Plot - Random Normal Variable")
qqline(log(cv_data$population), col = "gray")
hist(log(cv_data$population))
#testing normality of gdp
qqnorm(log(cv_data$gdp_capita), main = "QQ Plot - Random Normal Variable")
qqline(log(cv_data$gdp_capita), col = "gray")
hist(log(cv_data$gdp_capita))
#testing normality of rate
qqnorm(log(cv_data$rate), main = "QQ Plot - Random Normal Variable")
qqline(log(cv_data$rate), col = "gray")
hist(log(cv_data$rate))

```


##Challenge 6
```{r}
library(MASS)
library(AICcmodavg)
library(MuMIn)
(s<- stepAIC(model, scope = . ~ ., direction = "both"))
m1<-update(model, .~. -income)
summary(m1)
drop1(m1, test = "F")
m2<- update(m1, .~. -log(gdp_capita))
summary(m2)
drop1(m2, test = "F")
m3<- update(m2, .~. -log(population))
summary(m3)
#The best model is log(rate) ~ log(density)
bestm<- lm(log(rate)~log(density), data = cv_data)

#finding R^2 for them
r.squaredGLMM(model) #R squared values for the full model
r.squaredGLMM(bestm) # R squared values for the best model

#Repeating for daily infection rate
daily_model<- lm(log(cases)~ log(density) + log(population) + log(gdp_capita) + income, data = cv_data)
(s_daily<- stepAIC(daily_model, scope = .~., direction = "both"))
drop1(daily_model, test = "F")
daily2<- update(daily_model, .~. -log(population))
summary(daily2)
drop1(daily2, test = "F")
daily3<- update(daily2, .~. -log(gdp_capita))
summary(daily3)
drop1(daily3, test = "F") 
#Density is still the most importanat predictor, but this time income was a more important predictor than gdp_capita or population

r.squaredGLMM(daily_model) #R squared values for the full model
r.squaredGLMM(m3) # R squared values for the best model
```


##Challenge 7
```{r}
#testing normality of cases
qqnorm(log(cv_data$cases), main = "QQ Plot - Random Normal Variable")
qqline(log(cv_data$cases), col = "gray")
hist(log(cv_data$cases))

library(Rfast)
max_sd<- cv_data %>% group_by(country) %>% 


daily_model_update<- lm(log(cases) ~ log())
```


##Challenge 8
```{r}
cv_data_filtered<- cv_data %>% filter(population > 1000000 & variable == "daily_confirmed" & rate > 0)

library(lme4)
m1<- lmer(log(rate) ~ log(density) + log(gdp_capita) + soc_dist + mov_rest + (1|country) + (1|date), REML = FALSE, data = cv_data_filtered)
m2<- lmer(log(rate) ~ log(density) + log(gdp_capita) + soc_dist  + (1|country) + (1|date), REML = FALSE, data = cv_data_filtered)
m3<- lmer(log(rate) ~ log(density) + log(gdp_capita)  + (1|country) + (1|date), REML = FALSE, data = cv_data_filtered)
m4<- lmer(log(rate) ~ log(density) + (1|country) + (1|date), REML = FALSE, data = cv_data_filtered)
null<- lmer(log(rate) ~  (1|country) + (1|date), REML = FALSE, data = cv_data_filtered)

(aic_table <- aictab(list(m1, m2, m3, m4, null),
  modnames = c("full", "minusmov", "minussoc", "minusgdp", "null")
))#best model is the full model
r.squaredGLMM(m1) # R squared for the full/best model


```